name: Formatting
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Code Formatting and Trailing Whitespace Check
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Ruff for code formatting check
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.11.7
          args: "format --check --diff"

      - name: Run Ruff for linting check
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.11.7
          args: "check"
